language: node_js
node_js:
    - "0.10"
    - "0.8"
services:
    - couchdb
env:
    global:
        - NODE_ENV=test
before_install:
    - git clone git://github.com/mycozycloud/cozy-data-system.git
    - cd cozy-data-system 
    - npm install
    - pwd
    - start-stop-daemon --start --chdir /home/mycozycloud/cozy-proxy/cozy-data-system/ --exec /home/mycozycloud/cozy-proxy/cozy-data-system/server.coffee -b
    - cd ..
